# IMPORTANT: The Kubernetes cluster name
# https://docs.newrelic.com/docs/kubernetes-monitoring-integration
# cluster: ""

image:
  repository: fryckbos/pip
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 80M
  requests:
    cpu: 100m
    memory: 30M
